// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwYcCoaR0pRPli20r0LQIy3h-R1lHep1c',
    appId: '1:538465698343:web:3a4a9828507d30e7168402',
    messagingSenderId: '538465698343',
    projectId: 'smart-timetable-8f116',
    authDomain: 'smart-timetable-8f116.firebaseapp.com',
    storageBucket: 'smart-timetable-8f116.firebasestorage.app',
    measurementId: 'G-7P4CRC3CVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvXo7yeaDrMtoSq3wKxVPpTnE55X6U8W4',
    appId: '1:538465698343:android:05cf7b27ddffaae5168402',
    messagingSenderId: '538465698343',
    projectId: 'smart-timetable-8f116',
    storageBucket: 'smart-timetable-8f116.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZXUjEpsRmwaycy1yDWx0FnmpL2RnRjQ8',
    appId: '1:538465698343:ios:be5b1c2c7b680fa9168402',
    messagingSenderId: '538465698343',
    projectId: 'smart-timetable-8f116',
    storageBucket: 'smart-timetable-8f116.firebasestorage.app',
    iosClientId: '538465698343-pa9nvmjc2ttohir62gr2l01v9c66i9kd.apps.googleusercontent.com',
    iosBundleId: 'com.nova.smart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZXUjEpsRmwaycy1yDWx0FnmpL2RnRjQ8',
    appId: '1:538465698343:ios:be5b1c2c7b680fa9168402',
    messagingSenderId: '538465698343',
    projectId: 'smart-timetable-8f116',
    storageBucket: 'smart-timetable-8f116.firebasestorage.app',
    iosClientId: '538465698343-pa9nvmjc2ttohir62gr2l01v9c66i9kd.apps.googleusercontent.com',
    iosBundleId: 'com.nova.smart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwYcCoaR0pRPli20r0LQIy3h-R1lHep1c',
    appId: '1:538465698343:web:db4a6fb93b61fa11168402',
    messagingSenderId: '538465698343',
    projectId: 'smart-timetable-8f116',
    authDomain: 'smart-timetable-8f116.firebaseapp.com',
    storageBucket: 'smart-timetable-8f116.firebasestorage.app',
    measurementId: 'G-3EJNZ767M8',
  );
}
